#!/bin/zsh

clear

bold=`tput bold`
normal=`tput sgr0`
orange=`tput setaf 166`
white=`tput setaf 7`

echo "${bold}${orange}"
echo " MMMMMMMM                     MMMMMMM            CCCCCCC"
echo "    MMMMMM                   MMMMM          CCCCCCCCCCCCCCCCC"
echo "     MMMMMM                 MMMMM        CCCCC             CCCCC"
echo "     MMMMMMM               MMMMMM      CCCC                   CC"
echo "     MM  MMMM             MM  MMM     CCCC"
echo "     MM   MMMM           MM   MMM    CCCC"
echo "     MM    MMMM         MM    MMM    CCCC"
echo "     MM     MMMM       MM     MMM    CCCC"
echo "     MM      MMMM     MM      MMM    CCCC"
echo "     MM       MMMM   MM       MMM     CCCC"
echo "     MM        MMMM MM        MMM      CCCC                   CC"
echo "     MM         MMMMM         MMMM       CCCCC             CCCCC"
echo "    MMMM         MMM         MMMMMM         CCCCCCCCCCCCCCCCC"
echo " MMMMMMMMMM       M        MMMMMMMMMMM           CCCCCCC"
echo
echo "${white}================================================================="
echo
echo "    ${white}STATISTICS${normal}${white}"

df -h -x tmpfs -x udev -x devtmpfs | tail -n 1 | awk '{print "    Disk:      "$3" of "$2" ("$5" Full)"     }'

vmstat -s | head -n 2 | sed -e 's/ \{2,\}//g' -e 's/ K total memory//g' -e 's/ K used memory//g' | tr '\n' '\t' | awk -F \\t '{print "    Memory:    " sprintf("%.0f", $2 / 1024) "M of " expr $1 / 1024  "M (" sprintf("%.0f", $2 / $1 * 100) "% Used)"}'

cat /proc/loadavg | awk '{print "    Load:      "$1,$2,$3}'
echo
echo "${bold}${white}================================================================="
echo "${normal}"

