#!/bin/zsh

clear

megs=$[1024*1024]
gigs=$[1024*1024*1024]

vmstat=$(vm_stat)
pageSize=$(sed -nE 's/.*page size of ([0-9]+) bytes.*/\1/p' <<< "$vmstat")
pagesActive=$(sed -nE 's/.*Pages active: +([0-9]+)\./\1/p' <<< "$vmstat")
pagesWired=$(sed -nE 's/.*Pages wired down: +([0-9]+)\./\1/p' <<< "$vmstat")
pagesUsed=$[$pagesActive+$pagesWired]
memUsed=$(printf %0.2f $[$pagesUsed*$pageSize/$megs])
memTotal=$(printf %0.2f $[$(sysctl -n hw.memsize)/$megs])
memPercent=$(printf %d $[$memUsed/$memTotal*100])

rootVolume=$(df -H | grep -E "\/$" | awk '{print $3 " of " $2 " (" $5 " Full)"}')
load=$(sysctl -n vm.loadavg | sed -nE 's/\{ | \}//gp')

bold=`tput bold`
normal=`tput sgr0`
red=`tput setaf 1`
white=`tput setaf 7`

echo "${red}${bold}"
echo "   o8o               o8o                     o8o"
echo "   \`\"'               \`\"'                     \`\"'"
echo "  oooo  ooo. .oo.   oooo  ooo. .oo.  .oo.   oooo   .ooooo.  oooo  oooo   .oooo.o"
echo "  \`888  \`888P\"Y88b  \`888  \`888P\"Y88bP\"Y88b  \`888  d88' \`\"Y8 \`888  \`888  d88(  \"8"
echo "   888   888   888   888   888   888   888   888  888        888   888  \`\"Y88b."
echo "   888   888   888   888   888   888   888   888  888   .o8  888   888  o.  )88b"
echo "  o888o o888o o888o o888o o888o o888o o888o o888o \`Y8bod8P'  \`V88V\"V8P' 8\"\"888P'"
echo
echo "  ${white}=============================================================================="
echo
echo "      ${white}STATISTICS${normal}${white}"
echo "      Disk:     ${rootVolume}"
command printf "      Memory:   %'0.fM of %'0.fM (%d%% Used)\n" $memUsed $memTotal $memPercent
echo "      Load:     ${load}"
#echo "      Wired:\t"$[$pagesWired*$pageSize/$megs]
#echo "      Free:\t"$[$pagesFree*$pageSize/$megs]
#echo "      Active:\t"$[$pagesActive*$pageSize/$megs]
#echo "      Inactive:\t"$[$pagesInactive*$pageSize/$megs]
echo
echo "${white}${bold}  =============================================================================="
echo "${normal}"
