#!/bin/zsh

clear

megs=$[1024*1024]
gigs=$[1024*1024*1024]

vmstat=$(vm_stat)
pageSize=$(sed -nE 's/.*page size of ([0-9]+) bytes.*/\1/p' <<< "$vmstat")
pagesActive=$(sed -nE 's/.*Pages active: +([0-9]+)\./\1/p' <<< "$vmstat")
pagesWired=$(sed -nE 's/.*Pages wired down: +([0-9]+)\./\1/p' <<< "$vmstat")
pagesUsed=$[$pagesActive+$pagesWired]
memUsed=$(printf %0.2f $[$pagesUsed*$pageSize/$megs])
memTotal=$(printf %0.2f $[$(sysctl -n hw.memsize)/$megs])
memPercent=$(printf %d $[$memUsed/$memTotal*100])

rootVolume=$(df -H /System/Volumes/Data | tail -n 1 | awk '{print $3 " of " $2 " (" $5 " Full)"}')
load=$(sysctl -n vm.loadavg | sed -nE 's/\{ | \}//gp')

bold=`tput bold`
normal=`tput sgr0`
yellow=`tput setaf 3`
blue=`tput setaf 4`
white=`tput setaf 7`
dim=`tput dim`

echo "${blue}${bold}"
echo "   .oooo.o  .ooooo.  oooo d8b oooo    ooo  .ooooo.  oooo d8b ";
echo "  d88(  \"8 d88' \`88b \`888\"\"8P  \`88.  .8'  d88' \`88b \`888\"\"8P ";
echo "  \`\"Y88b.  888ooo888  888       \`88..8'   888ooo888  888     ";
echo "  o.  )88b 888    .o  888        \`888'    888    .o  888     ";
echo "  8\"\"888P' \`Y8bod8P' d888b        \`8'     \`Y8bod8P' d888b    ";
echo
echo "  ${white}========================================================== ";
echo
echo "      ${blue}STATISTICS${normal}${white}"
echo "      Disk:     ${rootVolume}"
command printf "      Memory:   %'0.fM of %'0.fM (%d%% Used)\n" $memUsed $memTotal $memPercent
echo "      Load:     ${load}"
#echo "      Wired:\t"$[$pagesWired*$pageSize/$megs]
#echo "      Free:\t"$[$pagesFree*$pageSize/$megs]
#echo "      Active:\t"$[$pagesActive*$pageSize/$megs]
#echo "      Inactive:\t"$[$pagesInactive*$pageSize/$megs]
echo
echo "  ${white}${bold}========================================================== ";
echo "${normal}"

