#!/bin/zsh

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

vim +PluginInstall +qall

setopt EXTENDED_GLOB;
for rcfile in ${ZDOTDIR:-$HOME}/.dotfiles/zprezto/runcoms/^README.md(.N); do
    ln -sf "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}";
done

if [ ! -e $HOME/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_client_support.so ]; then
    if [ -e $HOME/.vim/bundle/YouCompleteMe/install.py ]; then

        # The following additional language support options are available:
        #
        # - C# support: install Mono with Homebrew or by downloading the Mono macOS package and add --cs-completer when calling install.py.
        # - Go support: install Go and add --go-completer when calling install.py.
        # - JavaScript and TypeScript support: install Node.js and npm and add --ts-completer when calling install.py.
        # - Rust support: add --rust-completer when calling install.py.
        #   - If your Python interpreter is older than 2.7.9, you will also need rustup in your PATH.
        # - Java support: install JDK8 (version 8 required) and add --java-completer when calling install.py.
        #
        # To simply compile with everything enabled, there's a --all flag.
        # Note that this flag does not install clangd. You need to specify
        # it manually by adding --clangd-completer. So, to install with all
        # language features, ensure xbuild, go, tsserver, node and npm tools
        # are installed and in your PATH, then simply run:    
        #
        # cd ~/.vim/bundle/YouCompleteMe
        # ./install.py --all

        $HOME/.vim/bundle/YouCompleteMe/install.py \
            --ts-completer \
            --clangd-completer

    fi
fi

