#!/bin/zsh

clear

bold=`tput bold`
normal=`tput sgr0`
yellow=`tput setaf 3`
white=`tput setaf 7`

# TODO: Stick the below commands into vars to make
#       accessing them cleaner.

echo "${yellow}${bold}"
echo "                        oooo  oooo"
echo "                        \`888  \`888"
echo "  oooo    ooo  .ooooo.   888   888   .ooooo.  oooo oooo    ooo"
echo "   \`88.  .8'  d88' \`88b  888   888  d88' \`88b  \`88. \`88.  .8'"
echo "    \`88..8'   888ooo888  888   888  888   888   \`88..]88..8'"
echo "     \`888'    888    .o  888   888  888   888    \`888'\`888'"
echo "      .8'     \`Y8bod8P' o888o o888o \`Y8bod8P'     \`8'  \`8'"
echo "  .o..P'"
echo "  \`Y8P'  ${white}====================================================="
echo
echo "      ${white}${bold}LAST LOGIN${normal}${white}"
last -2Fwi | head -n 2 | tail -n 1 | sed -e 's/^\w\+\s\+\w\+\/\?\w\+\s\+//' -e 's/\s\+([0-9]\{2\}:[0-9]\{2\}\(:[0-9]\{2\}\)\?)\s*$//' -e 's/\w*still logged in\s*$/\tStill logged in/' -e 's/ - /\t/' -e 's/\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\)\s\+/\1\t/' | awk -F \\t '{print "      From:      "$1"\n      On:        "$2"\n      Until:     "$3}'
echo
echo "      ${white}${bold}STATISTICS${normal}${white}"
df -h -x tmpfs -x udev | tail -n 1 | awk '{print "      Disk:      "$3" of "$2" ("$5" Full)"}'
vmstat -s | head -n 2 | sed -e 's/ \{2,\}//g' -e 's/ K total memory//g' -e 's/ K used memory//g' | tr '\n' '\t' | awk -F \\t '{print "      Memory:    " sprintf("%.0f", $2 / 1024) "M of " expr $1 / 1024  "M (" sprintf("%.0f", $2 / $1 * 100) "% Used)"}'
cat /proc/loadavg | awk '{print "      Load:      "$1,$2,$3}'
echo
echo "  ${white}${bold}============================================================"
echo "${normal}"

#                     .+?????????+.
#                   /???????????????\\
#                 /??????????????????????????V
#               +????????????????????7
#            .???????????????????????
#          +????????????????????????
#      +???????????????????????????
#         T??????????????????????
#              Y?????????????7
